### ISSUE TITLE
Should we drop iOS 9 support

### ISSUE THREAD

**Issue by hfossli** [agens-no/EllipticCurveKeyPair#12]
Let me know in comments or with reactions what you prefer

👍 = drop support (minimum required iOS version will be 10)
👎 = please support iOS 9

**Comment by wuf810** [comment]
I'm conflicted…I think it good to keep support for iOS 9 but as we know it is so buggy and the new APIs are so much better to use.

My suggestion, create a branch and tag it as iOS 9 and then drop iOS 9 going forward.

**Comment by hfossli** [comment]
I like your proposal. I found a way to support iOS 9 without making breaking changes and without sacrificing API that much. https://github.com/agens-no/EllipticCurveKeyPair/pull/13

**Comment by hfossli** [comment]
I ended up having breaking changes to make iOS 10 and OS X first class citizens.. :+1:
