### ISSUE TITLE
How to use ECKeyPair without local authentication

### ISSUE THREAD

**Issue by dmwesterhoff** [agens-no/EllipticCurveKeyPair#15]
Not a bug report but rather a usage question:

I'd like to generate a key pair that is stored in the enclave, except where the private key can be used whenever the genuine app is running to sign/encrypt data, no local auth required. Could you provide guidance on the best way to achieve this?

**Comment by hfossli** [comment]
Awesome. Yep. Just change the access control :)

**Comment by hfossli** [comment]
Try this
`let accessControlPrivate = EllipticCurveKeyPair.AccessControl(protection: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, flags: [.privateKeyUsage])`

**Comment by wuf810** [comment]
Exactly as hfossil has shown it. This means no additional authentication is required etc. but does ensure that any signing is done in the secureEnclave.

**Comment by hfossli** [comment]
Reopen if you have further questions :)

**Comment by dmwesterhoff** [comment]
You guys are awesome. much appreciated.

**Comment by hfossli** [comment]
Thanks for using this library

**Comment by b00tsy** [comment]
Hi, thanks for providing this library. Makes my live less complicated :) 

I have a follow up question on that matter: I do as you suggest (using only `.privateKeyUsage` as flags, which results in that error: **throw EllipticCurveKeyPair.Error.inconcistency(message: "Couldn't create access control flag. Keychain chokes if you try to create access control with only [.privateKeyUsage] on devices older than iOS 11 and macOS 10.13.x")**

Is that meant to throw? I'm running this on iOS 12+ (getting it actually on iOS 14) and am wondering whether this should only throw for the iOS / macOS versions mentioned in the crash description.

Commenting those lines out that check if only `.privateKeyUsage` is set, everything works fine...

That's my code:

```
static let manager: EllipticCurveKeyPair.Manager = {
            let publicAccessControl = EllipticCurveKeyPair.AccessControl(protection: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, flags: [])
            let privateAccessControl = EllipticCurveKeyPair.AccessControl(protection: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, flags: {
                return EllipticCurveKeyPair.Device.hasSecureEnclave ? [.privateKeyUsage] : []
            }())
            let config = EllipticCurveKeyPair.Config(
                publicLabel: "public",
                privateLabel: "private",
                operationPrompt: "",
                publicKeyAccessControl: publicAccessControl,
                privateKeyAccessControl: privateAccessControl,
                token: .secureEnclaveIfAvailable)
            return EllipticCurveKeyPair.Manager(config: config)
        }()
```
