### ISSUE TITLE
Carthage and Frameworks support

### ISSUE THREAD

**Issue by kostiakoval** [agens-no/EllipticCurveKeyPair#3]
Can I add this project as a dependency to my workspace via Carthage or manually

**Comment by hfossli** [comment]
The problem is that I need some way to do the sha256 stuff. Currently that's something the users must provide. Maybe we'll then need to have a dependency to https://github.com/onmyway133/Arcane or https://github.com/krzyzanowskim/CryptoSwift.

**Comment by hfossli** [comment]
I'm thinking KISS – let the users of the library do this themselves.

**Comment by hfossli** [comment]
What I stated in February is not a problem anymore. Maybe we should use [SwiftPlate](https://github.com/JohnSundell/SwiftPlate) to create support for pods, carthage and swiftpm?

**Comment by hfossli** [comment]
Published 🎉
