### ISSUE TITLE
Publish new version in CocoaPods?

### ISSUE THREAD

**Issue by keefertaylor** [agens-no/EllipticCurveKeyPair#48]
Hi, 

The last publish / tagged version of this library was in November 2017 and there's been a lot of updates and helpful functionality pushed since then. While Carthage will let me consume the library from head, CocoaPods won't let another Pod consume an arbitrary version of a library.  Is it possible to publish a new version of this library in CocoaPods / Carthage?  

You should just be able to update the version numbers in the podspec, run `git tag` and `pod truck push`.

**Comment by hfossli-agens** [comment]
Thanks for reporting this issue. Master is updated, tag 2.0 is pushed, SPM is updated and podspec is pushed to cocoapods trunk.
