### ISSUE TITLE
Sign twice strings

### ISSUE THREAD

**Issue by MajidAlNuumani** [agens-no/EllipticCurveKeyPair#54]
Hello,

How can I sign two strings like (blaBla1) then (BlaBla2) in one call of 

`Shared.keypair.sign(digest, hash: .sha256)` and return two signatures

Thank you in advance?

**Comment by hfossli** [comment]
Why? 😆 Not possible afaik

**Comment by MajidAlNuumani** [comment]
I see @hfossli 

I need it to Register user and login user at once.

Thank you @hfossli
