### ISSUE TITLE
concern about userPresence

### ISSUE THREAD

**Issue by Lawati97** [agens-no/EllipticCurveKeyPair#57]
The code is 

` EllipticCurveKeyPair.Device.hasSecureEnclave ? [.userPresence, .privateKeyUsage] : [.userPresence]`

Will it be able to handle text passcode or should it be only Numeric value? (Other than FaceID if valid)

**Comment by hfossli** [comment]
Whatever the system supports. If the users phone is configured with FaceId it will try that first - if that fails it will fallback to pin/text/passcode. If not enrolled it will try pin/text/passcode directly. It supports both simple numeric pin and text as passcode.

**Comment by Lawati97** [comment]
because I tried using an Alphateic Passcode (Device Password for an IOS) and all of a sudden the face ID did not work
