### ISSUE TITLE
Access control is not respected 

### ISSUE THREAD

**Issue by badlands** [agens-no/EllipticCurveKeyPair#6]
Hi,
I faced issues when using your code with a kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly protection level.

```
        let protection = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
        let config = EllipticCurveKeyPair.Config(
            publicLabel: self.publicLabel,
            privateLabel: self.privateLabel,
            operationPrompt: "",
            accessControl: try! SecAccessControl.create(protection: protection, flags: [.privateKeyUsage]),
            fallbackToKeychainIfSecureEnclaveIsNotAvailable: true)
        return EllipticCurveKeyPair.Manager(config: config)
```

If you lock the device, wait a few seconds (10+), and you try to decrypt (I found it useful to trigger the decrypt method with a notification), you get this error:

`decode keys,rowid=760 failed (-25308): Error Domain=NSOSStatusErrorDomain Code=-25308 "ks_crypt: e00002e2 failed to 'od' item (class 6, bag: 0) Access to item attempted while keychain is locked." UserInfo={NSDescription=ks_crypt: e00002e2 failed to 'od' item (class 6, bag: 0) Access to item attempted while keychain is locked.}`

Class 6 is: kSecAttrAccessibleWhenUnlocked (see this thread on [SO](https://stackoverflow.com/questions/31197774/ios-8-notification-action-access-to-item-attempted-while-keychain-is-locked-e#31355906))

The item should not belong to Class 6.

I managed to solve this issue by applying this change:

```
        static func forceSavePublicKey(_ publicKey: PublicKey, label: String) throws {
            // I will create a SecAccessControl
            var error: Unmanaged<CFError>?
            
            let sacObject = SecAccessControlCreateWithFlags(kCFAllocatorDefault, kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, [], &error)
            //
            
            let query: [String: Any] = [
                kSecClass as String: kSecClassKey,
                kSecAttrLabel as String: label,
                kSecValueRef as String: publicKey.underlying,
                /* I will apply the SecAccessControl object to the public key */
                kSecAttrAccessControl as String: sacObject!,
            ]
            
            var raw: CFTypeRef?
            var status = SecItemAdd(query as CFDictionary, &raw)
            if status == errSecDuplicateItem {
                status = SecItemDelete(query as CFDictionary)
                status = SecItemAdd(query as CFDictionary, &raw)
            }
            guard status == errSecSuccess else {
                throw Error.osStatus(message: "Could not save public key", osStatus: status)
            }
        }
    } 
```

This is a rough patch, imho you should re-use what you already have in the Config object.

**Comment by hfossli** [comment]
Thank you for using this library and reporting this issue. I'll have a look.

**Comment by hfossli** [comment]
Okay, so basically what you are saying is if we don't provide any `kSecAttrAccessControl` when saving the key it will default to class 6 (`kSecAttrAccessibleWhenUnlocked`)?

**Comment by badlands** [comment]
Yes, that's what I have experienced.

**Comment by hfossli** [comment]
Allright, we've got two choices then. Either have an opinionated logic where we use the same access control for both private and public key.. Or we provide some api. 

1. What you suggested (same for both)

or

2. Change init for Config object
```
        public init(publicLabel: String,
                    privateLabel: String,
                    operationPrompt: String?,
                    publicKeyAccessControl: SecAccessControl,
                    privateKeyAccessControl: SecAccessControl,
                    fallbackToKeychainIfSecureEnclaveIsNotAvailable: Bool)
```

**Comment by hfossli** [comment]
I'm leaning towards second alternative

**Comment by badlands** [comment]
Yes, I was about to vote for option number 2.

**Comment by hfossli** [comment]
Did you otherwise find this library easy to use?

**Comment by badlands** [comment]
Yes. Thank you for sharing it!

**Comment by hfossli** [comment]
Can you try the branch `frameworks`? On that branch I have support for Carthage and Cocoapods as well if you rather use that. :)

Please note that the API changed slightly to this (delaying `try` on access control to a later point in time): 
```
    struct Shared {
        static let keypair: EllipticCurveKeyPair.Manager = {
            let accessControl = EllipticCurveKeyPair.AccessControl(protection: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, flags: [.userPresence, .privateKeyUsage])
            let config = EllipticCurveKeyPair.Config(
                publicLabel: "no.agens.encrypt.public",
                privateLabel: "no.agens.encrypt.private",
                operationPrompt: "Decrypt",
                publicKeyAccessControl: accessControl,
                privateKeyAccessControl: accessControl,
                fallbackToKeychainIfSecureEnclaveIsNotAvailable: true)
            return EllipticCurveKeyPair.Manager(config: config)
        }()
    }
```

**Comment by badlands** [comment]
Hi,
I'll try it, but I cannot do it in the next few days because I'll be on
holiday :-) I'll let you know if everything works fine.

**Comment by hfossli** [comment]
Me too 😆 enjoy 👋

**Comment by hfossli** [comment]
If you are using cocoapods it should be as easy as adding the following to your Podfile:

```
  pod 'EllipticCurveKeyPair', :git => 'https://github.com/agens-no/EllipticCurveKeyPair.git', :branch => 'frameworks'
```

**Comment by hfossli** [comment]
Were you able to test this? :)

**Comment by badlands** [comment]
Hi!
Yes I run a rapid test this morning and everything seems to be working!

Thanks!!!

**Comment by hfossli** [comment]
Awesome. Good to hear. Closing this issue once it is published on master and tagged.

**Comment by hfossli** [comment]
Thank you for reporting this! <3

**Comment by hfossli** [comment]
http://www.openradar.me/35069937

**Comment by hfossli** [comment]
Allright. This is now published and available on cocoapods, carthage and on master on this repo! Thanks again.
